# syntax=docker/dockerfile:1

FROM debian:11

WORKDIR /usr/src/app

RUN apt-get update 
RUN apt-get install -y wget gnupg2
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \ 
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && unzip curl
RUN apt-get -y install google-chrome-stable
RUN apt --fix-broken install

CMD /bin/bash
